chain_id: 1
grpc_data_stream_endpoint: grpc.mainnet.aptoslabs.com:443
grpc_data_stream_api_key: aptoslabs_2yJt7uuBKDk_8wc9UWBdecfW4ZTRogk4XBfnHgVBqdXnH
starting_version: 1204378406
db_connection_uri: "postgresql://postgres:localhost123@localhost:5432/example_event"
